version: '3'

services:
  app:
    container_name: rangers-blue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
