name: Rangers CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          RDS_HOST: ${{ secrets.RDS_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rangers:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rangers:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Pull Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/rangers:latest

      - name: Stop existing container
        run: |
          if [ $(sudo docker ps -q -f name=rangers) ]; then
            sudo docker stop rangers
          fi

      - name: Remove existing container
        run: |
          if [ $(sudo docker ps -a -q -f name=rangers) ]; then
            sudo docker rm rangers
          fi

      - name: Run new Docker container
        run: sudo docker run --rm -it -d -p 80:8080 --name rangers ${{ secrets.DOCKER_USERNAME }}/rangers:latest

      - name: Clean up unused Docker data
        run: sudo docker system prune -f
