name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]
  workflow_dispatch: # 수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # OS 환경
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: List files in build/libs
      run: ls -la build/libs

    - name: Docker build
      run: |
        docker build -t rangers:latest .

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_SERVER_HOST }}
        username: ubuntu
        key: key.pem
        source: |
          build/libs/rangers-0.0.1-SNAPSHOT.jar
          entry.sh
        target: "/home/ubuntu/app/"

    - name: SSH and switch containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_SERVER_HOST }}
        username: ubuntu
        key: key.pem
        script: |
          chmod +x /home/ubuntu/app/entry.sh
          sh /home/ubuntu/app/entry.sh
