name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: 현재 디렉토리 확인
      run: pwd

    - name: 루트 디렉토리 파일 목록 확인
      run: ls -la 

    - name: Docker build
      run: docker build -t rangers:latest .

    - name: 아티팩트 업로드
      uses: actions/upload-artifact@v2
      with:
        name: all-artifacts
        path: |
          build/libs/*.jar
          src/main/resources/application.yml
          entry.sh
          docker-compose.blue.yml
          docker-compose.green.yml
          nginx.blue.conf
          nginx.green.conf
          Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        name: all-artifacts
        path: /home/runner/work/Rangers-BE/Rangers-BE/

    - name: Check current directory
      run: pwd

    - name: List all required files
      run: |
        ls -la
        cat entry.sh 
        cat src/main/resources/application.yml
        cat docker-compose.blue.yml
        cat docker-compose.green.yml
        cat nginx.blue.conf
        cat nginx.green.conf
        cat Dockerfile

    - name: EC2로 파일 보내기
      uses: appleboy/scp-action@v0.1.1
      with:
        username: ubuntu
        host: ${{ secrets.EC2_SERVER_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: |
          ./build/libs/rangers-0.0.1-SNAPSHOT.jar
          ./entry.sh
          ./docker-compose.blue.yml
          ./docker-compose.green.yml
          ./nginx.blue.conf
          ./nginx.green.conf
          ./Dockerfile
          ./src/main/resources/application.yml
        target: "/home/ubuntu/app/"
        rm: true
        overwrite: true

    - name: 배포
      uses: appleboy/ssh-action@v0.1.1
      with:
        username: ubuntu
        host: ${{ secrets.EC2_SERVER_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: GITHUB_SHA
        script: |
          export IMAGE_TAG=${GITHUB_SHA::7}
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          chmod 777 /home/ubuntu/app/entry.sh
          /home/ubuntu/app/entry.sh $IMAGE_TAG $DOCKER_USERNAME
